### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [eapache/go-resiliency#10]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-resiliency and versioning would help Debian keep up with development.

**Comment by eapache** [comment]
Hey, there is already a `v1.0.0` git tag from last year which should be what you're looking for? The library is simple enough that there haven't been any other changes since then to warrant a new release. Let me know if you need something else.

**Comment by aviau** [comment]
Sorry, I am opening many bugs at the same time and somehow I missed that there were tags on your repository. Thanks!
