### ISSUE TITLE
Exponential backoff should have some jitter

### ISSUE THREAD

**Issue by doherty** [eapache/go-resiliency#12]
This minimizes the risk of correlated retries. Compare to goback's jitter: https://github.com/carlescere/goback#jitter-backoff

**Comment by doherty** [comment]
From page 270 of Google's SRE book:
> Always use randomized exponential backoff when scheduling retries. See also
> "Exponential Backoff and Jitter" in the AWS Architecture Blog [[Bro15]](https://landing.google.com/sre/book.html). If retries
> aren’t randomly distributed over the retry window, a small perturbation (e.g., a
> network blip) can cause retry ripples to schedule at the same time, which can
> then amplify themselves [[Flo94]](https://dl.acm.org/citation.cfm?id=187045).

**Comment by eapache** [comment]
You can call `SetJitter` to add jitter regardless of the backoff.
