### ISSUE TITLE
breaker_test.go:173: circuit breaker is open

### ISSUE THREAD

**Issue by aviau** [eapache/go-resiliency#14]
Hello!

We are getting the following error in the Debian CI:

```
--- FAIL: TestBreakerAsyncStateTransitions (4.03s)
	breaker_test.go:173: circuit breaker is open
FAIL
exit status 1
FAIL	gopkg.in/eapache/go-resiliency.v1/breaker	14.081s
=== RUN   TestDeadline
--- FAIL: TestDeadline (0.04s)
	deadline_test.go:27: timed out waiting for function to finish
FAIL
exit status 1
FAIL	gopkg.in/eapache/go-resiliency.v1/deadline	0.080s
=== RUN   TestConstantBackoff
```

full log: https://tests.reproducible-builds.org/debian/logs/buster/amd64/golang-gopkg-eapache-go-resiliency.v1_1.0.0-1.build2.log.gz

Looks like it only happens some of the time.

**Comment by eapache** [comment]
The test suite for this package includes a lot of timer-based tests which are unreliable if your test runner is slow or has a low-precision clock (both of which I believe happen to be true of Debian's CI).

I suppose ideally I would inject a controlled clock at the test level, but I've always been wary of anything in test that makes the production code less clean.
