### ISSUE TITLE
retrier: support context.Context

### ISSUE THREAD

**Issue by chrisguiney** [eapache/go-resiliency#16]
Greetings,
I'm a user of the retry package, mostly because it's a dependency of the shopify/sarama package - so it's already available in my vendor directory.

I'm interested to know if you'd be in favor of supporting the context package for retrier -- I imagine the interface to be

```go
(r *Retrier) RunCtx(context.Context, func() error) error
```
This would allow the retrier to exit early if the provided context is cancelled prior to the retry wait period.
If the context is cancelled, it could return the error of the last failure, or `ctx.Err()` - I'm unsure which would be preferred.

I would imagine the retier struct would need to be extended to include a time.Timer that would be reset upon each call to Run/RunCtx, and each iteration of attempts.

Exiting early would me a simple matter of having a function such as
```go
// sleep will return true if the time channel has a message
// sent on it before the context expires
//
// accepts a <-chan time.Time for more deterministic testing
// no need to rely on the runtime to fire the timer
func sleep(ctx context.Context, t <-chan time.Time) bool {
    select {
    case <-t:
        return true
    case <-ctx.Done():
        return false
    }
}
```

the call to time.Sleep() could then be replaced with

```go
if !sleep(ctx, r.timer.C) {
    // return previous error?
    return ctx.Err()
}
```

The implementation of `Run` could then become
```go
(r *Retrier) Run(fn func() error) error {
    return r.RunCtx(context.Background(), fn)
}
```

This approach is seen in the standard library, and is a nice way to maintain backwards compatibility.

Please let me know your thoughts - if this is something you'd approve of, I could likely find the time to do the implementation.

**Comment by chrisguiney** [comment]
>Should the func passed to RunCtx itself take the ctx as an argument in case it wants to cancel?

Personally, I don't think so - that'd make the signature read

```go
(r *Retrier) RunCtx(context.Context, func(context.Context) error
```

which sounds stuttery to me.   Speaking for myself, the function passed in is always a closure, so can easily have access to the context being passed to RunCtx anyway.

>me neither, I don't really have a concrete use case in mind

There are two that I have in mind:
1. Program exit, and not having to wait for the retrier to wake up.
2. A request exceeding its deadline and wishing to cancel any retries in flight

I think in both of these cases, I'd expect the ctx.Err() value to be returned.

>This would be equivalent to calling time.After each iteration, just more efficient?

Yes, it would avoid the re-allocation of the timer on each iteration

**Comment by eapache** [comment]
> Speaking for myself, the function passed in is always a closure, so can easily have access to the context being passed to RunCtx anyway

That's a good point.

> I think in both of these cases, I'd expect the ctx.Err() value to be returned.

Makes sense to me.

> if this is something you'd approve of, I could likely find the time to do the implementation.

I'd be happy to look at a PR of this.
