### ISSUE TITLE
Please release again

### ISSUE THREAD

**Issue by nim-nim** [eapache/go-resiliency#18]
The sole current release is missing years of fixes

**Comment by eapache** [comment]
"years of fixes" is a few documentation tweaks and a new helper method. Master has no unreleased bugfixes.

**Comment by nim-nim** [comment]
Well, duh, that's still years of work :)

**Comment by eapache** [comment]
v1.1 is now tagged :)

**Comment by nim-nim** [comment]
Thanks a lot !
