### ISSUE TITLE
goroutine leak in Deadline.Run

### ISSUE THREAD

**Issue by evolsnow** [eapache/go-resiliency#23]
if `Run()` returns `ErrTimeOut`, the work function would block on sending to  channel `result`.

**Comment by eapache** [comment]
The work function should only send to `result` in a `select` that also reads from `stopper`, which would be closed for this purpose.

**Comment by eapache** [comment]
Wait, what am I talking about, it can't because I hid that inside the goroutine you're talking about. Nice catch.
