### ISSUE TITLE
add log for breaker error

### ISSUE THREAD

**Issue by Stephan14** [eapache/go-resiliency#25]
I feel that you should add log when some occur in function `func (b *Breaker) doWork(state uint32, work func() error) error`, it convenient for us to find error

**Comment by eapache** [comment]
I'm not quite sure what your use case is. If an error occurs in the work function, it will be returned from `Run()`, or discarded from `Go()`, just like how running a function (or launching one with `go`) works without this library.

This library is intended to be a very low-level, foundational set of tools and so intentionally does not log anywhere, just as Go itself does not add any logs. If you want to add logging to the method you pass into the breaker, you are welcome to do that.

**Comment by Stephan14** [comment]
I see, I need add log in my function
