### ISSUE TITLE
Error unwrapping for `retrier/`

### ISSUE THREAD

**Issue by taufik-rama** [eapache/go-resiliency#28]
Hello, I've some feature request regarding the title

Basically, I propose we use [`errors.Is()`](https://pkg.go.dev/errors#Is) from standard library to check for the blacklisted/whitelisted error types (the `err == pass` bit)

https://github.com/eapache/go-resiliency/blob/b98ce2825f7276cc41027348986a241ef5d62fd8/retrier/classifier.go#L40-L44

The reason is that currently we need to specify _exacly_ what the error kind is, without checking if an error actually contains ("wraps") another error which are actually listed

Say we've implements a custom type to better handle specific error usecase

```Go
type HTTPError struct {
    error
    host string
    path string
}

func (h HTTPError) Error() string { // implements Go's `error` type
    return "failed on HTTP request to " + h.host + h.path + " reason: " + h.error.Error()
}

func (h HTTPError) Unwrap() error { // will be called from standard library error unwrapping
    return h.error
}
```

And that the error type wraps `context.Canceled`, which is defined as a blacklist

```Go

backoff := // ...
class := retrier.BlacklistClassifier{
	context.Canceled,
}
retry := retrier.New(backoff, class)

// ...

retry.Run(func() {
    // ...
    return HTTPError{error: context.Cancelled, host: "...", path: "..."}
})
```

The blacklist check would fail, because `err == pass` won't know what the "internal" value of the error actually is

**Comment by prozz** [comment]
Please consider this improvement. Would be really handy.

**Comment by eapache** [comment]
Sorry it took me a while to get to this. I am bumping the minimum Golang version so I can accept this PR. Previously of course you are welcome to use your own implementation of the `Classifier` interface with the rest of this package.
