### ISSUE TITLE
Support service oriented calls for retrier

### ISSUE THREAD

**Issue by eleduardo** [eapache/go-resiliency#33]
I like to use retrier to wrap calls to external services one thing that is generating a bit of verbose code right now is that the work functions do not return any value in their signature (totally understandable) .

The idea here would be to create a new Run/RunCtx signature using generics and make the work function return the type that is passed to the function... 

```
func (r *Retrier) RunR[R any](work func() (R, error)) error

func (r *Retrier) RunCtxR[R any](ctx context.Context, work func(ctx context.Context) (R, error)) error
```

This way the caller can just wrap their normal function without having to var the return... 

I understand this would force the library to jump all the way to go 1.18 but just wondering if you would be open to me PRing this..

I can also try to use some type of interface{} approach so that there is no need to go go 1.18

**Comment by peczenyj** [comment]
My two cents

it is not possible, even in go 1.21, add type parameters on methods. This syntax is not valid.

however we can have type parameters on functions and we can do something like this:

```go

func Run(r *Retrier, work func() error) error {
	return r.Run(work)
}

func Run2[T0 any](r *Retrier, work func() (T0, error)) (T0, error) {
	var (
		t0  T0
		err error
	)
	rerr := r.Run(func() error {
		t0, err = work()
		return err
	})

	return t0, rerr
}

func Run3[T0, T1 any](r *Retrier, work func() (T0, T1, error)) (T0, T1, error) {
	var (
		t0  T0
		t1  T1
		err error
	)
	rerr := r.Run(func() error {
		t0, t1, err = work()
		return err
	})

	return t0, t1, rerr
}
…
```
Complete example:
https://go.dev/play/p/B4Wlup-U-Kk

Since we are talking about add new functions, this solution is backward compatible and we don’t need to wait until a v2

**Comment by eapache** [comment]
Poked around with this a little bit. It looks like Go is not planning to support parameterized methods, and their reasoning seems sound: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#no-parameterized-methods

A generic shared `Runner` class or something like that is an interesting proposal which could solve several of these problems. I'm definitely willing to consider proposals or PRs for such ideas.

However, I'll reiterate that I don't have the time or interest to work on this myself.
