### ISSUE TITLE
Request for New Tag: Add Infinite Retry Option

### ISSUE THREAD

**Issue by maximebeckman** [eapache/go-resiliency#39]
Hello,
I recently made a change to the library and I would like new tag to be so I can rely on it, in my project. The specific change is the introduction of a new option called "WithInfiniteRetry()" allowing users to configure the retrier for infinite retry attempts.

### Change Details:

New option: WithInfiniteRetry()
Users can now set this option to enable infinite retries for scenarios where continuous retry attempts are desired.

### Why This Matters:
Infinite retries can be useful in scenarios where a user wants to continuously attempt an operation until success without a predefined limit. This change enhances the flexibility and adaptability of the retrier, catering to a wider range of use cases.
IMHO, it's supposed to be an alternativ to handle in a more proper way a panicOnError, in a transactional context.

### Request:
Can you please create a new tag for this enhancement, making it easier for users to integrate this feature into their projects. I understand and appreciate your time and effort in maintaining this library. 🙏 

Thank you for considering this request. If there are any additional details or steps required from my end, please let me know.

Thanks a lot !

**Comment by eapache** [comment]
Thanks for the reminder, should be done as v1.5.0.
