### ISSUE TITLE
infinite retries

### ISSUE THREAD

**Issue by egorlepa** [eapache/go-resiliency#53]
add support for infinite retries somehow? I can of course do
```
ConstantBackoff(math.MaxInt32) 
```
but it'll allocate a huge array

perhaps an option to simply repeat last duration
or ability to pass a function for lazy evaluation instead of []Duration
or make use of rangefuncs of go 1.23 to provide a lazy evaluated infinite range of durations

**Comment by eapache** [comment]
I'm not sure that there's much value in this library supporting infinite retries, that's basically just a `for { }` loop which you don't need a library for?

**Comment by eapache** [comment]
In general, the cases where you need infinite retries are not "resiliency" cases so much.

**Comment by tukeJonny** [comment]
I agree with eapache.
Infinite retries means no plan, with no change of recovery.

Basically, It's more constructive to have a plan to cover the failed process as a result of consuming all retries than to have it retry for an unrealistic amount of time.

Also, there is not much the library can guarantee in an infinite retries.
Then it is reasonable to deal with it at your own risk.
